name: Test Plugins

on:
  pull_request:
  workflow_dispatch:

jobs:
  get-plugins:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - id: plugin_names
        run: echo "::set-output name=plugins::$(curl -s https://api.napari-hub.org/plugins | jq -c 'keys')"
    outputs:
      plugins: ${{ steps.plugin_names.outputs.plugins }}

  test:
    needs: get-plugins
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        plugin: ${{ fromJson(needs.get-plugins.outputs.plugins) }}
        python-version: [3.9]
        platform: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: tlambert03/setup-qt-libs@v1

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install napari PySide2 pytest

      - name: Install ${{ matrix.plugin }}
        run: pip install ${{ matrix.plugin }}

      - name: Test plugin on PySide2
        run: pytest .github/workflows/test_plugin.py
        env:
          NAPARI_PLUGIN: ${{ matrix.plugin }}

      - name: Switch backend
        run: |
          pip uninstall -y PySide2 shiboken2
          pip install PyQt5

      - name: Test plugin on PyQt5
        run: pytest .github/workflows/test_plugin.py
        env:
          NAPARI_PLUGIN: ${{ matrix.plugin }}
