name: Test Plugins

on:
  pull_request: {}
  workflow_dispatch:

jobs:
  get-plugins:
    runs-on: ubuntu-latest
    steps:
      - id: plugin_names
        run: echo "::set-output name=plugins::$(curl -s https://api.napari-hub.org/plugins | jq -c 'keys')"
    outputs:
      plugins: ${{ steps.plugin_names.outputs.plugins }}

  test:
    needs: get-plugins
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        plugin: ${{ fromJson(needs.get-plugins.outputs.plugins) }}
        python-version: [3.9]
        platform: [macos-latest, windows-latest]

    steps:
      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: tlambert03/setup-qt-libs@v1

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install napari PyQt5

      - name: Install plugin
        run: pip install ${{ matrix.plugin }}

      - name: Test plugin
        run: pytest .github/workflows/test_plugin.py
        env:
          PLUGIN: ${{ matrix.plugin }}

      - name: Switch backend
        run: |
          pip uninstall -y PyQt5
          pip install PySide2

      - name: Test plugin
        run: pytest .github/workflows/test_plugin.py
        env:
          PLUGIN: ${{ matrix.plugin }}
